name: "Simple Main Branch Test Workflow"

on:
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send a test message
        run: echo "This is a test message from the GitHub Actions workflow on the main branch."

  run:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple command
        run: echo "Running a simple command in the workflow on the main branch."
